### ISSUE TITLE
Add GDPR module

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#148]
https://www.drupal.org/project/gdpr

We should add this for our EMEA team. Similar to SEO, this can quickly be enabled to not only provide some examples of GDPR in action, but also a checklist for GDPR confirmation. 

The idea is to use the demo to help illustrate concepts and eliminate objections quickly.

**Comment by saltednut** [comment]
We have a few modules for this use case already here, so we can add this. https://github.com/acquia/df/blob/8.x-4.x/modules/df/df_tools/df_tools_gdpr/df_tools_gdpr.info.yml

**Comment by saltednut** [comment]
@rlnorthcutt do you think we should enable any of the submodules that come with gdpr when enabling `df_tools_gdpr` ?

**Comment by rlnorthcutt** [comment]
I think enabling `df_tools_gdpr` should enable any other modules necessary to have a standard GDPR setup. So, the question is - whats the desired standard? I'll reach out to the team and find out more.

**Comment by saltednut** [comment]
A while back I worked with the docs team to try to tease out a standard and there wasn't a lot of consensus or opinions partially due to the USA-based team and both myself (issuer) and the people writing the docs (issued) didn't know what was best? Anyway, we came up with this. So I'd arm myself with it lest someone else find it and provide it to you as a "new resource" : https://docs.acquia.com/resource/gdpr/

**Comment by saltednut** [comment]
Removing ip_anon and eu_cookie_compliance because gdpr_consent and anonymiser both take care of those operations inside the gdpr suite.
