### ISSUE TITLE
Fatal error viewing revision

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#155]
Steps to reproduce:
1) Create/publish content
2) Create publish revision
3) View list of revisions (https://mike1-acsfdemo6-prod.acquia-demo.com/node/16/revisions)
4) Click on the initial revision to generate the error

DBLOG:

> Error: Call to a member function bundle() on string in radix_theme_suggestions_page_alter() (line 10 of /mnt/www/html/acsfdemo601live/docroot/themes/contrib/radix/includes/suggestions.inc)

**Comment by kevinfunk** [comment]
Radix already had an issue for it https://www.drupal.org/project/radix/issues/3008219 and was fixed in the 8.x-4.4 release. DF 4 was updated to Radix 8.x-4.4 with commit [939cef9](https://github.com/acquia/df/commit/939cef9ebf7355897bad84b9dfcaaf1598e15661). I'm closing this since it will be fixed on the next codebase update.
