### ISSUE TITLE
Add DF version number to the Status report page in Drupal

### ISSUE THREAD

**Issue by rlnorthcutt** [acquia/df#216]
I know it might a bit to the process, but if we are able to add the DF version number to the status page in Drupal, then it will make support easier. When someone has a problem, especially what sounds like an old problem or one that we recently fixed, we can easily find out if "update your code" is the fix.

**Comment by saltednut** [comment]
On drupal.org/project/df ?

**Comment by saltednut** [comment]
Is this in reference to a specific issue that was filed?

**Comment by rlnorthcutt** [comment]
Yes, on the DF repo. There isn't a specific issue, I'm just thinking of how we have had issues in the past where we have spent some time trying to help someone only to find out that they just needed to update the codebase.

It would be great to be able to say:
"Are you on the latest version (4.x.y)? Lets update that first"

Just a thought. If its too much of a pain, we don't _need_ to do it.

**Comment by saltednut** [comment]
Just to be clear, this project here is the canonical DF repo, and the one on Drupal is basically a mirror. We only push to it to back up things and we do not tag releases there in the drupal format or promote a drupal.org based tarball, as we can't support such things.  I am not opposed to updating the project page to link to the latest release on github.

That said, this sounds like its a problem you have with SE's at Acquia probably more than partners or customers?  So it would seem this is an acquia/demo_framework release problem, not an open source release problem?

I just don't know who this is for, who it helps and when that happens.  Was this stemmed by not knowing what the latest release number was? That's pretty easy to check on this repo here?

If its the desire of anyone at any time to be able to download and run the latest release, then it probably makes the most sense to direct people from the drupal.org project page to acquia/df-project as it is designed to always download and install the latest stable release.

**Comment by saltednut** [comment]
As a followup, I've taken the necessary steps to fix the DF project.  I think we can and should probably update the DF project when there's a new release, even though its not necessary usually, just to make sure its not broken. It had not been working since we removed lightning-dev from the repo. That's my bad.

**Comment by saltednut** [comment]
I think another thing we should do is put info on how to use the df-project on drupal.org and also on the main project page.  That would at least solve this problem for OSS users.  To solve the issues with SE's, we need to ensure they always use the latest version.

But I still don't understand why we couldn't always do this:
> "Are you on the latest version (4.x.y)? Lets update that first"

If this conversation is between us and an SE that needs help, we should be going to the release page on github such as https://github.com/acquia/demo_framework/releases (for the SE's that have access, otherwise for OSS people - https://github.com/acquia/df/releases)

When checking those, you can typically see a module version # or whatever that's been updated. Typically core. For example, 4.0.2 brings us up to 8.8.4 - so then we check on the environment and see their core version and cross reference this.

There's no actual way with distros to report the current distro/profile version, that I know of. The best you can do is look at what version of core they have running and cross reference.

So, for the sake of argument, lets say I do edit the drupal.org/project/df page adding "Latest version on github: 4.0.2" right?

So here's the use case one more time:

> we have had issues in the past where we have spent some time trying to help someone only to find out that they just needed to update the codebase.

> It would be great to be able to say:
> "Are you on the latest version (4.x.y)? Lets update that first"

Okay so now you've gone to Drupal.org and you know 4.0.2 is the latest version because Brant logged in and edited the drupal project page.  You have no other information other than the DF version number. You can't check on your drupal in the cloud and ask it what DF it is, it doesn't know. It knows its running 8.8.2 though. So then you are back to github.  Looks like 8.8.2 was tied to 4.0.0 - we found this by looking at the releases page on github. https://github.com/acquia/df/releases

**Comment by rlnorthcutt** [comment]
Sorry - I don't think I did a good job of explaining what I meant. My thought was to use `hook_requirements` to add an INFO check to the Drupal status page (/admin/reports/status). Then it would be easy to find out what the latest DF for any site.

<img width="786" alt="demo-framework-status" src="https://user-images.githubusercontent.com/673633/78055164-ba614d80-7348-11ea-8e4f-d976e2476514.png">

**Comment by saltednut** [comment]
Okay that's a totally different thing and has nothing to do with the drupal.org project page.

**Comment by saltednut** [comment]
I see what you were saying now and I re-read what you wrote. We can definitely provide that via code. The confusion came here:

> On drupal.org/project/df ?

> Yes, on the DF repo. 

lol

Totally thought you were talking about the project page.

**Comment by saltednut** [comment]
> There's no actual way with distros to report the current distro/profile version, that I know of. 

> My thought was to use hook_requirements to add an INFO check to the Drupal status page (/admin/reports/status)

I stand corrected.  Let's just change the issue title and say yes, we'll do this.

**Comment by saltednut** [comment]
I think this is actually GTG.  Just a process change after all.
